services:
  - type: web
    name: learning-log
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn learning_log.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: RENDER
        value: True
      - key: DATABASE_URL
        fromDatabase:
          name: learning-log-db
          property: connectionString

databases:
  - name: learning-log-db
    databaseName: learning_log_prod
    user: learning_log_user
    plan: free
    region: frankfurt